/* global db print */
/* eslint no-restricted-globals: "off" */

db.reviews.remove({});
db.deleted_reviews.remove({});
db.deleted_issues.remove({});

const reviewsDB = [
  {
    id: 1,
    title: 'Modern Physics PH 241',
    reviewer: 'Professor Connover',
    courseName: 'Modern Physics PH 241',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2017-01-01'),
    answer1: '',
    answer2: 'Lots of labs, lab reports, long problem sets, and exams were brutal',
    answer3: 'I learned a lot in the course but sometimes office hours was frustrating.',
    answer4: 'A lot, I had more of a struggle or issue with just the amount of work and lack of available help. If there was help, students sometimes felt put down.',
    additional: '',
  },
  {
    id: 2,
    title: 'EC224',
    reviewer: 'Findlay',
    courseName: 'EC224',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2019-01-01'),
    answer1: '',
    answer2: '',
    answer3: '',
    answer4: '',
    additional: '',
  },
  {
    id: 3,
    title: 'EA273',
    reviewer: 'Weitz',
    courseName: 'EA273',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2020-01-01'),
    answer1: 'If you practice being insightful and talking about the things she asks for you you\'ll quickly learn what she\'ll give an A for. She can tell who cares about the material and who doesn\'t.',
    answer2: 'A brief reading for each class, a weekly reflection (3-5 sentences), and a weekly quiz. It\'s is all very interesting and doesn\'t feel as heavy as it would if it were physics homework.',
    answer3: 'Great teacher. Loves the material and helping her students understand it.',
    answer4: 'Extremely interesting class for any major. Professor Weitz\'s understanding and love for teaching the class were evident in the curiosity she sparked in her students.',
    additional: '',
  },
  {
    id: 4,
    title: 'CH147',
    reviewer: 'Conry',
    courseName: 'CH147',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2020-01-01'),
    answer1: 'Didn\'t grade exams and homework hard but labs she treats like scripture.',
    answer2: 'An hour\'s worth of studying or doing MasteringChem every night... And then the weekly lab is due. The labs are the most boring uninformative thing ever, what makes them difficult is that you basically have to copy your entire lab down twice according to a set of requirements they don\'t tell you about until after they\'ve given you a C for doing it wrong. The most disorganized and confusing lab I\'ve ever taken even though the material was painfully easy to understand.',
    answer3: 'Basically not at all. Her office hours were twice a week but every week they were different. It\'s like she was trying throw us off, I never knew when to go.',
    answer4: 'It\'s all material from High School so needless to say I was bored.',
    additional: '',
  },
  {
    id: 5,
    title: 'PS223',
    reviewer: 'Goh',
    courseName: 'PS223',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2020-01-01'),
    answer1: 'Fair.',
    answer2: 'Two readings and a page-long reflection per week. Few projects and exams spread across the semester. Not difficult to manage, even less so if you take notes in class and engage with the material.',
    answer3: '',
    answer4: 'Extremely interesting. Shows how social psychologists prove through experimentation not only how social groups form but what prejudices and harmful effects they cause. You will also be made to think of ways to solve issues of prejudice before learning what has been shown to work.',
    additional: '',
  },
  {
    id: 6,
    title: 'BI274',
    reviewer: 'Ahmad',
    courseName: 'BI274',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2020-01-01'),
    answer1: 'Fair. Demanded exactly the degree of understanding appropriate to someone that cared about the course and wanted to learn the material well and improve where they didn\'t.',
    answer2: 'Weekly quiz, weekly lab, and a monthly exam. There was not a shred of homework which outside of these. This is the style of teaching which has been proven by many neuroscientists to be most effective so its fitting taht this course would work this way. Students are given the time to go to office hours and study what they think they need to; basically, students who care about learning the material most will do better, as it was meant to be.',
    answer3: 'Always available',
    answer4: '',
    additional: '',
  },
  {
    id: 7,
    title: 'The Political Economy of Regionalism',
    reviewer: 'Walter Hatch',
    courseName: 'The Political Economy of Regionalism',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2018-01-01'),
    answer1: '',
    answer2: '',
    answer3: 'I chose this as my favorite because I learned by far the most out of any class at Colby! And it was so challenging in the best way.',
    answer4: '',
    additional: '',
  },
  {
    id: 8,
    title: 'EC318',
    reviewer: 'Lindsay Novak',
    courseName: 'EC318',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2020-01-01'),
    answer1: 'Really clear guidance on the difficulty of the exams, which were derived entirely from Problem Sets.',
    answer2: 'Readings are front-loaded on the semester to help you understand theory, followed by journal articles for discussion in the latter half. There is a large research project, but it is segmented really nicely so that it is never extremely stressful.',
    answer3: '',
    answer4: 'Really clear lecturing style, good slides and great ability to break down the theoretical equations.',
    additional: '',
  },
  {
    id: 9,
    title: 'EC234 Macroeconomic Theory',
    reviewer: 'Dave Findlay',
    courseName: 'EC234 Macroeconomic Theory',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2019-01-01'),
    answer1: 'Answers had to be thorough and could not leave a single thing out. Having said that, for most questions there was opportunity for partial credit.',
    answer2: 'Readings and problem sets took a long time.',
    answer3: 'The most I\'ve gotten out of a class at Colby. Prof. Findlay\'s passion for teaching was evident. I was both nervous and excited for most of his classes. If you have the chance to take a class with Findlay and you\'re up for a challenge, I highly recommend.',
    answer4: 'Lectures were never boring. Just be prepared to get called on.',
    additional: '',
  },
  {
    id: 10,
    title: 'CS343 Neural Networks',
    reviewer: 'Oliver Layton',
    courseName: 'CS343 Neural Networks',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2020-01-01'),
    answer1: 'He was pretty nice with grading and was lenient about extending deadlines whenever needed.',
    answer2: 'The projects took a lot of time and some of the concepts were difficult to fully understand. Luckily, we were able to partner up which made the load more manageable.',
    answer3: 'Yes, I believed Oliver was very dedicated to helping us learn and his office hours were really useful.',
    answer4: 'Oliver seemed very experienced with neural networks and was able to answer any of our questions about them.',
    additional: '',
  },
  {
    id: 11,
    title: 'ES212 GIS and remote sensing',
    reviewer: 'Philip Nyhus, Manny Gimond',
    courseName: 'ES212 GIS and remote sensing',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2017-01-01'),
    answer1: 'Pretty hard in terms of grade of assignments. And the workload is heavy. However, it really helps towards using GIS.',
    answer2: 'A lot of in class practice and after class exercise',
    answer3: 'Very. Philip really cares about his students both work wise and in other aspects. He is a great person to turn to if you need someone to talk to.',
    answer4: 'Philip use GIS through his phd and is hired by Colby first as GIS specialist and so is Manny. Both of them are proficient in the subject',
    additional: '',
  },
  {
    id: 12,
    title: 'BI163 The Cellular Basis of Life',
    reviewer: 'Tilden',
    courseName: 'BI163 The Cellular Basis of Life',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2016-01-01'),
    answer1: 'Pretty generous and lenient grader.',
    answer2: 'Class notes were extensive, exams were thorough and difficult. Class went fast and it was all memorization.',
    answer3: 'Yes, but was not always great at breaking down information to the simplest form.',
    answer4: 'Very skilled in cellular biology and very kind.',
    additional: '',
  },
  {
    id: 13,
    title: 'GO131 INTERNATIONAL RELATIONS',
    reviewer: 'Hatch',
    courseName: 'GO131 INTERNATIONAL RELATIONS',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2016-01-01'),
    answer1: 'Prettt strict but its very fair. He lets you know wxamxtly what hes looking for and provides opportunities to help you along the way.',
    answer2: 'SO MUCH READING. you also had to stay updated on current events.',
    answer3: 'Yes, very much. Especially in teaching students how to learn without being U.S.-centric.',
    answer4: 'He was ceey well versed in readings and even wrote some himself.',
    additional: '',
  },
  {
    id: 14,
    title: 'EC393 Econometrics',
    reviewer: 'Lafave',
    courseName: 'EC393 Econometrics',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2019-01-01'),
    answer1: 'Right or wrong answers. I\'d say on a scale of 1 to 10, 6.',
    answer2: 'Weekly assignments, pop quizzes, mid term and final',
    answer3: 'Yes I believe so',
    answer4: 'Very well.',
    additional: '',
  },
  {
    id: 15,
    title: 'TD252 B Choreography for camera',
    reviewer: 'Ann Kloppenberg',
    courseName: 'TD252 B Choreography for camera',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2019-01-01'),
    answer1: 'Fairly strict',
    answer2: 'There was not as much reading compared to other classes in terms of length, but we had readings for almost every class',
    answer3: 'Very much',
    answer4: 'She had a sound knowledge of the choreography aspect, but I think she was still building up her expertise in the connection between it and camerawork',
    additional: '',
  },
  {
    id: 16,
    title: 'EC214',
    reviewer: 'Patrice Franko',
    courseName: 'EC214',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2018-01-01'),
    answer1: 'Quite strictly',
    answer2: 'Heavy amount of work, espeically for a 200-level class. A solid amount of reading and quite a bit of writing (I beleive it might have been a W2 as well).',
    answer3: 'Very much. She demanded a lot but was alwasy availble to help',
    answer4: 'Very well. She literally wrote the book on the topic - the core of our readings came from her textbook',
    additional: '',
  },
  {
    id: 17,
    title: 'Genocide and globalization',
    reviewer: 'Van der Meer',
    courseName: 'Genocide and globalization',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2018-01-01'),
    answer1: 'Letter grade, pretty strict',
    answer2: 'The course load is okay. Easy to handle',
    answer3: 'Yes',
    answer4: 'Very well and he cares about it',
    additional: '',
  },
  {
    id: 18,
    title: 'PH141 foundations of mechanics',
    reviewer: 'Jonathan McCoy',
    courseName: 'PH141 foundations of mechanics',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2016-01-01'),
    answer1: 'They were graqdly fairly. Students were given partial credit if part of the question was correct or tackled correctly.',
    answer2: 'The workload was good! Weekly problem sets and a quiz every Friday as well, but it didn\'t overload students with work.',
    answer3: '"Yes!! 100% Professor McCoy cared a lot about our learning and held various office hours and gave us the resources to improve."',
    answer4: 'Very well. Professor McCoy taught this perfectly for an intro course to physics. He structured it to make Physics as understandable as possible for incoming new physics students.',
    additional: '',
  },
  {
    id: 19,
    title: 'CS361',
    reviewer: 'Dale Skrien',
    courseName: 'CS361',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2018-01-01'),
    answer1: 'I would said Dale was one of the more struck graders I had at Colby. Definitely the most strict in the CS department.',
    answer2: 'There was a significant amount of work for this class. Workload was made up of group projects, invdividual homework assignments, quizzes, and exams.',
    answer3: 'I think Dale was one of the most passionate professors I had a Colby. He took a lot of time to talk with me one-on-one about material unrelated to the courses I had him for.',
    answer4: 'Dale was very experienced and was a leading expert in the subject of this course.',
    additional: '',
  },
  {
    id: 20,
    title: 'ES218',
    reviewer: 'Manny Gimond',
    courseName: 'ES218',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2018-01-01'),
    answer1: 'Normal.',
    answer2: 'Many tutorials. Really fun.',
    answer3: 'Yes.',
    answer4: 'Very well.',
    additional: '',
  },
  {
    id: 21,
    title: 'MU234 History of Rock and Roll',
    reviewer: 'Professor Natasha Zelensky',
    courseName: 'MU234 History of Rock and Roll',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2018-01-01'),
    answer1: 'Easier than average. The final exams are not too easy though.',
    answer2: 'Not a lot of workload. But had to listen to many songs to be familiar with each time period.  There are a bunch of listening exams.',
    answer3: 'Yes, she cared a lot.',
    answer4: 'Very well.',
    additional: '',
  },
  {
    id: 22,
    title: 'EC211 Corporate Finance',
    reviewer: 'Professor Fan',
    courseName: 'EC211 Corporate Finance',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2020-01-01'),
    answer1: 'Fairly hard',
    answer2: 'Two problem sets a week with 3 exams and a project throughout the semester',
    answer3: 'Yes, I really enjoyed being in professor Fans class',
    answer4: 'Professor Fan was an excellent teacher of economics and clearly knew the material',
    additional: '',
  },
  {
    id: 23,
    title: 'EN278 - Fiction Writing I',
    reviewer: 'Sarah Braunstein',
    courseName: 'EN278 - Fiction Writing I',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2018-01-01'),
    answer1: 'Not strict! It was a Creative Writing class so the professor was very liberal about grading us and focused on our improvement.',
    answer2: 'We wrote a couple short stories. How much work we put in to the stories was up to us. She was also good at meeting us where we were at and adjusting, which was great for my mental health. There was a lot of reading in my opinion. It was a bit too excessive in the sense that I wanted more time to write my own stuff, but other than that the workload was fine.',
    answer3: 'The professor cared a lot about her students and we trusted her a lot. She was always willing to help her students. She was also really flexible and let her students take charge of their own projects. She was really good at supporting our visions.',
    answer4: 'She knew Creative Writing really well. She had so many books to recommend to us and individual writers. She gave great advice and provided us amazing feedback.',
    additional: '',
  },
  {
    id: 24,
    title: 'MA162',
    reviewer: 'Ben Mathes',
    courseName: 'MA162',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2020-01-01'),
    answer1: 'The weekly homework assignments are graded by the TAs quite fairly. Late homework submission can also receive full credits. The exams are graded by the profosser, and Ben is absolutely not a hard grader. He normally gives everybody an A or A-.',
    answer2: 'It takes long time to think of answers to the proof questions in the homework, and TA hours will save you some time when you get helpless.',
    answer3: 'Ben is a super enthusiastic professor who loves drawing mouse as his special notation during his lecture. He is super nice and friendly, and his office hours are helpful.',
    answer4: 'The course materials for Honors Calculus are not easy, especially those involving proofs. It is not easy to catch up and completely follow the professor in class, so it is necessary to review your notes after class and go to office hours.However, things get much easier when you finish studying proofs and start with multivariable calculus.',
    additional: '',
  },
  {
    id: 25,
    title: 'AY421',
    reviewer: 'Chandra Bhimull',
    courseName: 'AY421',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2020-01-01'),
    answer1: '',
    answer2: 'The workload was a lot, but you really got out of the class what you put into it. If you apply yourself and do a deep dive into the readings, you will get an insane amount from this class.',
    answer3: 'Chandra is incredible. She is a no joke kind of lady, but she is brilliant, kind, and dedicated to her students. She is willing and eager to take the class on a journey. This will be your favorite class because of her and the environment she creates not for us, but with us.',
    answer4: 'SO MUCH. This class was largely discussion based, but Chandra offered words and thoughts throughout, and they were always immensely helpful. She knows how to direct a conversation, ground it in theory and ideas, and move it along so that we all slowly stretch our brains.',
    additional: '',
  },
  {
    id: 26,
    title: 'EC 336: mathematical economics',
    reviewer: 'Robert lester',
    courseName: 'EC 336: mathematical economics',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2016-01-01'),
    answer1: '',
    answer2: '',
    answer3: '',
    answer4: 'Robert is soooooooooo goooooooood! Love him :)',
    additional: '',
  },
  {
    id: 27,
    title: 'AR101 Reading images',
    reviewer: 'Veronique Plesch',
    courseName: 'AR101 Reading images',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2019-01-01'),
    answer1: 'She definitely a very knowledgeable professor, but she doesn\'t know how to convey what\'s in her mind to her students. She asked us to refine our third draft based on her comments for our second draft, but she gave back our second draft a week after her deadline for our third draft. I would love to take more of her lectures but not when that may affect my gpa cuz she\'s a strict grader',
    answer2: '',
    answer3: '',
    answer4: '',
    additional: '',
  },
  {
    id: 28,
    title: 'PS232 Cognitive Psychology',
    reviewer: 'Jen Coane',
    courseName: 'PS232 Cognitive Psychology',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2018-01-01'),
    answer1: 'Exams and assignments are not easy. The exam questions were given before exam so she is looking for very thorough understanding of the concepts and experiments and expressd',
    answer2: 'The overall workload was ok. There was not a lot of reading. The textbook is the complimentary material for the lectures so you can skip the reading if you feel you understand the lectures, but you may need additional time to review course materials to fully understand them.',
    answer3: 'Yes. She held office hours frequently. She also had two TAs on call.',
    answer4: 'Very well. The course was very well-designed.',
    additional: '',
  },
  {
    id: 29,
    title: 'MA122',
    reviewer: 'Tamar Friedmann',
    courseName: 'MA122',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2019-01-01'),
    answer1: 'Very strict. She even admits that she is particularly strict when grading exams.',
    answer2: 'Problem set every week. We had to go to TA hours to get the homework done.',
    answer3: 'Only offers very limited office hours. Not very helpful.',
    answer4: 'Not good at explaining concepts or answering questions',
    additional: '',
  },
  {
    id: 30,
    title: 'MA122',
    reviewer: 'Michael Dougherty',
    courseName: 'MA122',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2020-01-01'),
    answer1: 'average',
    answer2: '',
    answer3: '',
    answer4: '',
    additional: '',
  },
  {
    id: 31,
    title: 'CH141',
    reviewer: 'Lindsey Madison',
    courseName: 'CH141',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2018-01-01'),
    answer1: 'The professor is pretty strict bc it is a science subject',
    answer2: 'The workload is not heavy.',
    answer3: 'yes, she hosts regular office hours and asks for feedback to her classes',
    answer4: 'She is effective in her teaching',
    additional: '',
  },
  {
    id: 32,
    title: 'SO131',
    reviewer: 'Prof. Neil L. Gross',
    courseName: 'SO131',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2017-01-01'),
    answer1: 'The professor is not very strict in grading',
    answer2: 'The workload is not too much. I had weekly readings, midterms and a final paper.',
    answer3: 'Yes, the students would ask students to talk to him one on one before the final assignments.',
    answer4: 'The professor is very effective in his teaching and has good use of class materials.',
    additional: '',
  },
  {
    id: 33,
    title: 'PS111',
    reviewer: 'Prof. Soto, Coane, Buccigrossi, Tarja, Seto',
    courseName: 'PS111',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2018-01-01'),
    answer1: 'Each professor has their own guidelines. Generally not very strict.',
    answer2: 'The workload varies with each professor. The bio and developmental part has a bit of workload because it is just a lot of information to memorize.',
    answer3: 'Yes. The professors give out study guides and office hours.',
    answer4: 'The professors are very effective in their teaching.',
    additional: '',
  },
  {
    id: 34,
    title: 'CS152 Computational Thinking: Scientific Applications',
    reviewer: 'Zadia Codabux (former visiting professor)',
    courseName: 'CS152 Computational Thinking: Scientific Applications',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2018-01-01'),
    answer1: 'Everything seemed to be graded fairly.',
    answer2: 'The workload was huge but that was expected as this is a CS class.',
    answer3: 'She definitely wanted to teach students but I don\'t think she was very good at making the material accessible.',
    answer4: 'She seemed to be shaky in python and much more comfortable with java, which was a challenge, but her knowledge of general computer science concepts did help.',
    additional: '',
  },
  {
    id: 35,
    title: 'MA121',
    reviewer: 'Professor Mathes',
    courseName: 'MA121',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2019-01-01'),
    answer1: 'He graded them moderately strictly.',
    answer2: 'The workload was not exactly light, but it was manageable.',
    answer3: 'Yes, he was very enthusiastic.',
    answer4: 'He knew it very well.',
    additional: '',
  },
  {
    id: 36,
    title: 'MA122',
    reviewer: 'Michael Dougherty',
    courseName: 'MA122',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2020-01-01'),
    answer1: 'Prof seems very fair with grading. Not overly strict or lenient.',
    answer2: 'Moderate-high but consistent and manageable.',
    answer3: 'Yes.',
    answer4: 'Exceptionally well.',
    additional: 'Professor Dougherty is an exceptional math teacher.',
  },
  {
    id: 37,
    title: 'MA121',
    reviewer: 'Owad',
    courseName: 'MA121',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2019-01-01'),
    answer1: 'Very leniently',
    answer2: 'Light workload',
    answer3: 'Yes',
    answer4: 'The professor was very passionate about math and tried to make sure every student understood the material',
    additional: '',
  },
  {
    id: 38,
    title: 'MA122',
    reviewer: 'Gabriel',
    courseName: 'MA122',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2019-01-01'),
    answer1: 'Normally strict...',
    answer2: 'The homework is a bit too much--there are a lot of questions and some of them are hard and time consuming',
    answer3: 'Yes, definitely; he tries to make everything crystalline clear and tries to answer every question students have',
    answer4: 'Very well',
    additional: '',
  },
  {
    id: 39,
    title: 'MA122',
    reviewer: 'Michael Dougherty',
    courseName: 'MA122',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2020-01-01'),
    answer1: 'Normal',
    answer2: 'Every week, there is a 4-paper homework.',
    answer3: 'Yes',
    answer4: 'Very good, the professor can explain evey point with example and in an interesting way.',
    additional: '',
  },
  {
    id: 40,
    title: 'BI163',
    reviewer: 'Ron Peck',
    courseName: 'BI163',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2019-01-01'),
    answer1: 'Normal.',
    answer2: 'It is easy for the lecture but busy for the lab.',
    answer3: 'Yes',
    answer4: 'Good, but his lecture is a little hard. There are no points reinforced.',
    additional: '',
  },
  {
    id: 41,
    title: 'CS231',
    reviewer: 'Bruce Maxwell',
    courseName: 'CS231',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2019-01-01'),
    answer1: 'Median.',
    answer2: 'A lot more than CS151 since the projects were more difficult.',
    answer3: 'Median. The prof was willing to help students during office hour but his class notes were not good for reviewing since they were all handwritten. No PPT was used.',
    answer4: 'Very well.',
    additional: '',
  },
  {
    id: 42,
    title: 'CS151',
    reviewer: 'Oliver Layton',
    courseName: 'CS151',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2018-01-01'),
    answer1: 'Median.',
    answer2: 'Median. Although there were weekly project due that made every week busy, there was no midterms.',
    answer3: 'Yes. The powerpoints are detailed and the prof was very willing to offer help during office hours.',
    answer4: 'Although it was the first course of the prof at my college, I think he knows well on the course materials.',
    additional: '',
  },
  {
    id: 43,
    title: 'MA122',
    reviewer: 'Evan Randles',
    courseName: 'MA122',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('20198-01-01'),
    answer1: 'Median.',
    answer2: 'Median. There are a lot of criteria like HW, group projects, written assignments, and quizes. The workload is not a lot but there are many different kinds of things to work on.',
    answer3: 'I think so. The course is an intro course of Math so the professor designed the course to have a lot of activities other than HWs, which made the course interactive since he gave comments for each of them.',
    answer4: 'Very well.',
    additional: '',
  },
  {
    id: 44,
    title: 'JA125',
    reviewer: 'Laura Nuffer',
    courseName: 'JA125',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2019-01-01'),
    answer1: 'Strict, but little point deductions.',
    answer2: 'Light.',
    answer3: 'Very.',
    answer4: 'Very.',
    additional: '',
  },
  {
    id: 45,
    title: 'MA161',
    reviewer: 'Ben Mathes',
    courseName: 'MA161',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2019-01-01'),
    answer1: 'Not very strict. Sometimes only parts of the exams were graded.',
    answer2: 'High.',
    answer3: 'Yes, but the professor was not very accessible.',
    answer4: 'Very well, but students sometimes had troble understanding the class.',
    additional: '',
  },
  {
    id: 46,
    title: 'EC223',
    reviewer: 'Erin Giffin',
    courseName: 'EC223',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2019-01-01'),
    answer1: 'Ordinary standard. The grading is out of 100 and partial points are given.',
    answer2: 'The workload is okay, but students need to go to office hours for answers.',
    answer3: 'She did a really good job in office hours and care about her students.',
    answer4: 'EC223 is one of her specialties so she knows the topics quite well.',
    additional: '',
  },
  {
    id: 47,
    title: 'MA122',
    reviewer: 'Leo Livshits',
    courseName: 'MA122',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2018-01-01'),
    answer1: 'The homework was extremely hard compared to other MA122 sessions. Students only get the lower score between correctness and writeup. However, Leo gives a really good curve so that the final grade would match Colby\'s distribution.',
    answer2: 'The assignments were difficult and students really need TA sessions and office hours.',
    answer3: 'Yes. He is really helpful in the office hours.',
    answer4: 'He is a very experienced professor and knows the topics very well.',
    additional: '',
  },
  {
    id: 48,
    title: 'CS151',
    reviewer: 'Oliver Layton',
    courseName: 'CS151',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2018-01-01'),
    answer1: 'The grading rubric for projects was more strict and hard to get a high score. For now, it is getting better.',
    answer2: 'The workload was okay for an introduction course. But students need more instructions as new programmers.',
    answer3: 'Yes.',
    answer4: 'Oliver knows the topic well, even though this was his first course in Colby.',
    additional: '',
  },
  {
    id: 49,
    title: 'CS231',
    reviewer: 'Hannah Wolfe',
    courseName: 'CS231',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2019-01-01'),
    answer1: 'Very strict.',
    answer2: 'Hours and hours every week. If you are good at CS, 5hrs. If not, it takes forever.',
    answer3: 'Yes.',
    answer4: 'Not really lol',
    additional: '',
  },
  {
    id: 50,
    title: 'MA122',
    reviewer: 'Bontea',
    courseName: 'MA122',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2019-01-01'),
    answer1: 'Extremely harsh. Some of the student graders are not smart at all and the rubric sucks.',
    answer2: '30mins everyday',
    answer3: 'Hard to say.',
    answer4: 'Not as good as my high school teacher.',
    additional: 'If you did one small question wrong, you should expect a B on exam',
  },
  {
    id: 51,
    title: 'EC134',
    reviewer: 'Rob Lester',
    courseName: 'EC134',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2019-01-01'),
    answer1: 'It depends on the students grader, but the problem sets are not hard at all. It\'s mainly algebra calculation.',
    answer2: 'It\'s very light. You could spend just 2 hours for the problem set per week.',
    answer3: 'Yes he did.',
    answer4: 'He knows everything about the course content.',
    additional: 'He is a nice and easygoing prof.',
  },
  {
    id: 52,
    title: 'EC223 Microtheory',
    reviewer: 'Erin Giffin',
    courseName: 'EC223 Microtheory',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2019-01-01'),
    answer1: 'Fairly strict',
    answer2: 'Overwhelming.',
    answer3: 'Yes.',
    answer4: 'Very well',
    additional: 'A bit too hard compared to the same course taught by other instructors. The professor is a nice person, but the workload and difficulty were kind of overwhelming. I have to admit that this course caused me to lose interest in economics.',
  },
  {
    id: 53,
    title: 'PS251 Personaloty Psychology',
    reviewer: 'Christopher Soto',
    courseName: 'PS251 Personaloty Psychology',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2019-01-01'),
    answer1: 'Fairly strict. No curves.',
    answer2: 'Not overwhelming.',
    answer3: 'Yes.',
    answer4: 'Very well.',
    additional: 'Professor values participation a lot. I seldom raised my hand in class, so I didn\'t get full credit on my participation, which hurted my overall grade.',
  },
  {
    id: 54,
    title: 'EC224',
    reviewer: 'Samara Gunter',
    courseName: 'EC224',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2017-01-01'),
    answer1: 'Grading of hw is a little harsh',
    answer2: 'A problem set every week. So not laborious',
    answer3: 'Yes',
    answer4: 'Very well',
    additional: '',
  },
  {
    id: 55,
    title: 'EC223',
    reviewer: 'Samara Gunter',
    courseName: 'EC223',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2018-01-01'),
    answer1: 'She is not a hard grader.',
    answer2: 'The workload was reasonable. I never stayed up late because of her assignments, but still got a good grade.',
    answer3: 'She was a really passionate teacher.',
    answer4: 'She is an expert in micro theory.',
    additional: '',
  },
  {
    id: 56,
    title: 'MA122',
    reviewer: 'Fernando Gouvea',
    courseName: 'MA122',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2017-01-01'),
    answer1: 'Relatively easy.',
    answer2: 'There was a problem set ever week and also reafing reflection.',
    answer3: 'Yes',
    answer4: 'Very thoroughly',
    additional: '',
  },
  {
    id: 57,
    title: 'EC224',
    reviewer: 'Professor Robert Lester',
    courseName: 'EC224',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2021-01-01'),
    answer1: 'I think the grading was very fair',
    answer2: 'Weekly assignments. Normal workload.',
    answer3: 'Yes. Rob was very accessible during office hours. He even has additional office hours on Sunday afternoons.',
    answer4: 'He wrote a textbook with professors from other colleges, which indicates that he knows the material pretty well.',
    additional: 'My opinions are obviously biased since Rob is my advisor and he\'s like a big brother to me.',
  },
  {
    id: 58,
    title: 'EC223',
    reviewer: 'Professor Tim Hubbard',
    courseName: 'EC223',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2021-01-01'),
    answer1: 'I think the grading was pretty fair',
    answer2: 'Weekly problem sets. Normal workload.',
    answer3: 'Tim cares a lot about his students. Very helpful during office hours and accessible outside office hours, too.',
    answer4: 'He knows everything in that course.',
    additional: 'Tim fan here!',
  },
  {
    id: 59,
    title: 'MA122',
    reviewer: 'Professor Fernando Gouvea',
    courseName: 'MA122',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2021-01-01'),
    answer1: 'Honestly don\'t remember much since I took it in freshman fall. Before the first midterm, a lot of materials overlapped with my high school math course.',
    answer2: 'Normal math course workload, nothing too surprising.',
    answer3: 'I think so',
    answer4: 'I think he knows the material pretty well. It\'s a 100 level class anyway',
    additional: '',
  },
  {
    id: 60,
    title: 'EC224',
    reviewer: 'Rob Lester',
    courseName: 'EC224',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2021-01-01'),
    answer1: 'It was okay',
    answer2: 'Weekly problem set',
    answer3: 'Yes',
    answer4: 'Very well',
    additional: '',
  },
  {
    id: 61,
    title: 'EC223',
    reviewer: 'Tim Hubbard',
    courseName: 'EC223',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2021-01-01'),
    answer1: 'It was okay',
    answer2: 'Weekly problem set',
    answer3: 'Yes absolutely',
    answer4: 'Very well',
    additional: '',
  },
  {
    id: 62,
    title: 'MA122',
    reviewer: 'David Krumm',
    courseName: 'MA122',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2021-01-01'),
    answer1: 'It was okay',
    answer2: 'Weekly problem set',
    answer3: 'Yes',
    answer4: 'Very well',
    additional: '',
  },
  {
    id: 63,
    title: 'EC234',
    reviewer: 'Rob Lester',
    courseName: 'EC234',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2021-01-01'),
    answer1: 'Quite strict. The exams were graded harshly and the homework was long.',
    answer2: '3-4 hours a week at least for homework.',
    answer3: 'Yes. He was very caring.',
    answer4: 'It was ok. The math part I totally got. But the actual Econ part was quite confusing. Its further application was also very obscure. I kinda hated Econ afterward.',
    additional: 'I hate Economics.',
  },
  {
    id: 64,
    title: 'MA122',
    reviewer: 'Fernando Q. Gouvêa',
    courseName: 'MA122',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2021-01-01'),
    answer1: 'Not too bad.',
    answer2: 'The problem set is alright, but the extra paper could be tough sometimes.',
    answer3: 'Yes he does.',
    answer4: 'He knows it really well, and his class is fun.',
    additional: '',
  },
  {
    id: 65,
    title: 'W1 Food for Thought',
    reviewer: 'Elisabeth F. Stokes',
    courseName: 'W1 Food for Thought',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2021-01-01'),
    answer1: 'Not too bad.',
    answer2: 'Just right. Lighter than other W1 class.',
    answer3: 'Very much.',
    answer4: 'The class is mainly through the discussion of the reading material. She prompts the discussion properly, and subject is really fun for a food lover.',
    additional: '',
  },
  {
    id: 66,
    title: 'CS151',
    reviewer: 'Dale Skrien',
    courseName: 'CS151',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2021-01-01'),
    answer1: 'Not too bad.',
    answer2: 'Just right.',
    answer3: 'Very much.',
    answer4: 'He knows a lot. He explains it very clearly, and he is very open to questions.',
    additional: 'Take any class with Dale. You will not regret!',
  },
  {
    id: 67,
    title: 'EC134',
    reviewer: 'Professor James Siola',
    courseName: 'EC134',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2021-01-01'),
    answer1: 'No, but he grades exams very carefully',
    answer2: 'More than EC133',
    answer3: 'He is a good teacher',
    answer4: '',
    additional: '',
  },
  {
    id: 68,
    title: 'EC134',
    reviewer: 'Professor James Siola',
    courseName: 'EC134',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2021-01-01'),
    answer1: 'Easy grader',
    answer2: 'Light workload',
    answer3: 'He is very nice to students and explains concepts clearly',
    answer4: '',
    additional: '',
  },
  {
    id: 69,
    title: 'EC134',
    reviewer: 'Professor James Siola',
    courseName: 'EC134',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2021-01-01'),
    answer1: 'Easy grader',
    answer2: 'Not much homework',
    answer3: 'Very nice to students.He teaches clearly',
    answer4: '',
    additional: '',
  },
  {
    id: 70,
    title: 'EC134',
    reviewer: 'Professor David Findlay',
    courseName: 'EC134',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2021-01-01'),
    answer1: '',
    answer2: 'A lot',
    answer3: 'Very passionate. I have learned a lot.',
    answer4: '',
    additional: '',
  },
  {
    id: 71,
    title: 'EC134',
    reviewer: 'Professor David Findlay',
    courseName: 'EC134',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2021-01-01'),
    answer1: 'Tough grader',
    answer2: 'A lot',
    answer3: 'His class will get you well-prepared for the econ theory classes. He cares deeply about students.',
    answer4: '',
    additional: '',
  },
  {
    id: 72,
    title: 'EC134',
    reviewer: 'Professor David Findlay',
    courseName: 'EC134',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2021-01-01'),
    answer1: 'Tough grader',
    answer2: 'A lot',
    answer3: 'I really like him. He is a passionate teacher who will teach you a lot of useful knowledge',
    answer4: '',
    additional: '',
  },
  {
    id: 73,
    title: 'EC134',
    reviewer: 'Professor David Findlay',
    courseName: 'EC134',
    createdDate: new Date('2021-08-06'),
    courseDate: new Date('2021-01-01'),
    answer1: 'Tough grader',
    answer2: 'A lot',
    answer3: 'He is very patient and will help you understand class material well.',
    answer4: '',
    additional: '',
  },
];

db.reviews.insertMany(reviewsDB);
const count = db.reviews.count();
print('Inserted', count, 'reviews');

db.reviews.createIndex({ id: 1 }, { unique: true });
db.reviews.createIndex({ title: 1 });
db.reviews.createIndex({ reviewer: 1 });
db.reviews.createIndex({ courseName: 1 });
db.reviews.createIndex({ createdDate: 1 });
db.reviews.createIndex({ courseDate: 1 });
db.reviews.createIndex({ answer1: 1 });
db.reviews.createIndex({ answer2: 1 });
db.reviews.createIndex({ answer3: 1 });
db.reviews.createIndex({ answer4: 1 });
db.reviews.createIndex({ additional: 1 });

db.deleted_reviews.createIndex({ id: 1 }, { unique: true });
db.counters.remove({ _id: 'reviews' });
db.counters.insert({ _id: 'reviews', current: count });
